// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/pb/proxy/geo_provider/geo_provider.proto

package geo_provider_contracts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GeoProviderClient is the client API for GeoProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeoProviderClient interface {
	Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error)
	SearchAddresses(ctx context.Context, in *SearchAddressesRequest, opts ...grpc.CallOption) (*SearchAddressesResponse, error)
}

type geoProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoProviderClient(cc grpc.ClientConnInterface) GeoProviderClient {
	return &geoProviderClient{cc}
}

func (c *geoProviderClient) Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error) {
	out := new(GeocodeResponse)
	err := c.cc.Invoke(ctx, "/geoprovider_contracts.GeoProvider/Geocode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoProviderClient) SearchAddresses(ctx context.Context, in *SearchAddressesRequest, opts ...grpc.CallOption) (*SearchAddressesResponse, error) {
	out := new(SearchAddressesResponse)
	err := c.cc.Invoke(ctx, "/geoprovider_contracts.GeoProvider/SearchAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoProviderServer is the server API for GeoProvider service.
// All implementations must embed UnimplementedGeoProviderServer
// for forward compatibility
type GeoProviderServer interface {
	Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error)
	SearchAddresses(context.Context, *SearchAddressesRequest) (*SearchAddressesResponse, error)
	mustEmbedUnimplementedGeoProviderServer()
}

// UnimplementedGeoProviderServer must be embedded to have forward compatible implementations.
type UnimplementedGeoProviderServer struct {
}

func (UnimplementedGeoProviderServer) Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Geocode not implemented")
}
func (UnimplementedGeoProviderServer) SearchAddresses(context.Context, *SearchAddressesRequest) (*SearchAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAddresses not implemented")
}
func (UnimplementedGeoProviderServer) mustEmbedUnimplementedGeoProviderServer() {}

// UnsafeGeoProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoProviderServer will
// result in compilation errors.
type UnsafeGeoProviderServer interface {
	mustEmbedUnimplementedGeoProviderServer()
}

func RegisterGeoProviderServer(s grpc.ServiceRegistrar, srv GeoProviderServer) {
	s.RegisterService(&GeoProvider_ServiceDesc, srv)
}

func _GeoProvider_Geocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoProviderServer).Geocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geoprovider_contracts.GeoProvider/Geocode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoProviderServer).Geocode(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoProvider_SearchAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoProviderServer).SearchAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geoprovider_contracts.GeoProvider/SearchAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoProviderServer).SearchAddresses(ctx, req.(*SearchAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoProvider_ServiceDesc is the grpc.ServiceDesc for GeoProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geoprovider_contracts.GeoProvider",
	HandlerType: (*GeoProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Geocode",
			Handler:    _GeoProvider_Geocode_Handler,
		},
		{
			MethodName: "SearchAddresses",
			Handler:    _GeoProvider_SearchAddresses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pb/proxy/geo_provider/geo_provider.proto",
}
